import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub,} from 'react-icons/ai';
import Image from 'next/image';
import deved from "../public/dev-ed-wave.png";
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import {useState} from 'react';

export default function Home() {
  const[darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode? 'dark': " "}>
     <Head>
       <title>Swarupa P Portfolio</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
     </Head>

     <main className="bg-white px-10 md:px-20 dark:bg-gray-900 lg:px-40">
      <section className="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between dark:text-white">
        <h1 className="text-xl font-burtons">Swarupa</h1>

        <ul className="flex items-center">
        <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" href="#">About me</a></li>
        <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" href="#">Projects</a></li>
        <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" href="#">Blog</a></li>
        <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" href="#">Projects</a></li>
          <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" href="#">Resume</a></li>
          <p className="ml-8"><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer" /></p>
        </ul>
        </nav>
        <div className="text-center p-10">
          <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl lg:text-12xl dark:text-teal-400">Swarupa P</h2>
          <h3 className='text-2xl py-2 dark:text-white md:text-3xl'>Designer and Developer.</h3>
          <p className="text-md py-5 leading8 text-gray-800 md:text-xl dark:text-gray-200 max-w-lg mx-auto">snhdfgshgfjsfkjkgjfgjhdscsnbvhjgvsdhvnbjvhgsujfmdsgfsgdhfjmnsdfjdshfjdsfbsjbf</p>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
          <a href="https://twitter.com/swarupap3">
  <AiFillTwitterCircle /> </a>
  <a href="https://www.linkedin.com/in/swarupap/" >  <AiFillLinkedin /></a>
  <a href="https://github.com/Swarupa567" >
  <AiFillGithub />
  </a>
</div>
        </div>
        <div className=" relative mx-auto bg-gradient-to-b  from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
        <Image src={deved} alt="hgfdshfj" layout="fill" object-fit="cover" />
        </div>
      <div>
        <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talented people to create digital products
              for both business and consumer use.</p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsa, saepe.
              </p>
      </div>
      <div className="lg:flex gap-10">
        <div className="text-center shadow-lg p-10 rounded-xl dark:bg-white my-10">
          <Image src={design} alt="hghdfgshdf" width={100} height={100} className="ml-12" />
          <h3 className="text-lg font-medium pt-8 pb-2">Beautiful designs</h3>
          <p className="py-2">
            {" "}
            Creating elegant designs suited for your needs following core design theory.
          </p>
          <h4 className="py-4 text-teal-600">Design tools I use</h4>
          <p className="text-gray-800 py-1">Photoshop</p>
          <p className="text-gray-800 py-1">Illustrator</p>
          <p className="text-gray-800 py-1">Figma</p>

        </div>
        <div className="text-center shadow-lg p-10 rounded-xl dark:bg-white my-10">
          <Image src={code} alt="hghdfgshdf" width={100} height={100} className="ml-12" />
          <h3 className="text-lg font-medium pt-8 pb-2">Beautiful designs</h3>
          <p className="py-2">
            {" "}
            Creating elegant designs suited for your needs following core design theory.
          </p>
          <h4 className="py-4 text-teal-600">Design tools I use</h4>
          <p className="text-gray-800 py-1">Photoshop</p>
          <p className="text-gray-800 py-1">Illustrator</p>
          <p className="text-gray-800 py-1">Figma</p>

        </div>
        <div className="text-center shadow-lg p-10 rounded-xl dark:bg-white my-10">
          <Image src={consulting} alt="hghdfgshdf" width={100} height={100} className="ml-12" />
          <h3 className="text-lg font-medium pt-8 pb-2">Beautiful designs</h3>
          <p className="py-2">
            {" "}
            Creating elegant designs suited for your needs following core design theory.
          </p>
          <h4 className="py-4 text-teal-600">Design tools I use</h4>
          <p className="text-gray-800 py-1">Photoshop</p>
          <p className="text-gray-800 py-1">Illustrator</p>
          <p className="text-gray-800 py-1">Figma</p>

        </div>
      </div>
      </section>
   <section>
  <div>
    <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
    <p className="text-md py-2 leading-8 dark:text-gray-200  text-gray-800">
      Since the beginning of my journey as a freelance designer and
      developer, I've done remote work for
      <span className="text-teal-500"> agencies </span>
      consulted for <span className="text-teal-500">startups </span>
      and collaborated with talented people to create digital products
      for both business and consumer use.</p>
      <p className="text-md py-2 leading-8 dark:text-gray-200  text-gray-800 dark:text-gray-200">
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsa, saepe.
        </p>
  </div>
   <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
    <div className="basis-1/3 flex-1 ">
      <Image src={web1} className="rounded-lg object-cover" alt="web1" width={100} height={100} layout="responsive"/>
    </div>
    <div className="basis-1/3 flex-1">
  <Image src={web2} alt="web2" className="rounded-lg object-cover"  width={100} height={100} layout="responsive" />
</div>
<div className="basis-1/3 flex-1">
  <Image src={web3} alt="web3" className="rounded-lg object-cover"  width={100} height={100} layout="responsive"/>
</div>
<div className="basis-1/3 flex-1">
  <Image src={web4} alt="web4" className="rounded-lg object-cover"  width={100} height={100} layout="responsive"/>
</div>
<div className="basis-1/3 flex-1">
  <Image src={web5} alt="web5" className="rounded-lg object-cover"  width={100} height={100} layout="responsive" />
</div>
<div className="basis-1/3 flex-1">
  <Image src={web6} alt="web6" className="rounded-lg object-cover"  width={100} height={100} layout="responsive"/>
</div>
   </div>
</section>
     </main>
    </div>
  )
}
